### ISSUE TITLE
add support for "bm2sm.exceptions.UnsupportedControlFlowError" for ogg only type conversions

### ISSUE THREAD

**Issue by ultrabear** [DeltaEpsilon7787/BM2SMConverter#10]
I have read through the errors page and found that the issue with these blocks is they are not supported in SM, i have .bms files that i want to convert to just plain .ogg files and I believe it should be possible to make the converter support these blocks for music only conversion, I however have no knowledge of how to parse bms audio so I ask as a suggestion to make it support the blocks that normally go into 
``` 
   def _puke_from_gimmicks(self, _=0):
        raise UnsupportedControlFlowError
```
when it is in audio only mode, I tried just cutting the code that errors, but the audio file returned broken

**Comment by DeltaEpsilon7787** [comment]
I took a look at it.

So basically the issue with control flow gimmicks is that they allow variation in files. This converter bakes keysounds into the final audio file and keysounds are usually assigned to a note. Control flow gimmicks make it possible to make a file that can literally sound different each time. This converter is also pretty old and I've never gotten around to improving it and it just so happened it's a very strict deterministic conversion.

For your case, I suggest manually picking a specific random number and resolving the control flow sections.

**Comment by ultrabear** [comment]
thanks for the feedback, ill try that, the concept that the song can sound different is quite silly, especially since its a BMS of Aleph-0 that im trying to convert, sidenote if you ever do get around to improving old features, id suggest an output format option
